**One Hot Encoding**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df.shape

(8128, 5)

In [5]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

**1. OneHotEncoding using Pandas**

In [7]:
n_cols=pd.get_dummies(df, columns=['fuel', 'owner'], sparse=True, dtype=int)   
#converts categories into dummy vars (dummy columns) with values 0 and 1

In [8]:
n_cols.sample(5)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6203,Skoda,40000,900000,0,1,0,0,1,0,0,0,0
144,Toyota,39000,625000,0,0,0,1,1,0,0,0,0
984,Hyundai,80000,900000,0,1,0,0,0,0,1,0,0
2473,Maruti,80000,270000,0,0,0,1,1,0,0,0,0
6782,Tata,271000,50000,0,1,0,0,1,0,0,0,0

In [9]:
n_cols.shape

(8128, 12)

**2. K-1 OneHotEncoding**

In [10]:
n_minus_1_cols = pd.get_dummies(df, columns=['fuel', 'owner'], dtype=int, drop_first=True)

In [11]:
n_minus_1_cols.sample(5)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
364,Nissan,120000,250000,1,0,0,0,0,0,0
5054,Maruti,60000,300000,0,0,1,0,0,0,0
3499,Renault,40000,350000,0,0,1,0,0,0,0
5302,Ford,40000,625000,1,0,0,1,0,0,0
2763,Hyundai,57000,200000,0,0,1,0,0,0,0

In [12]:
n_minus_1_cols.shape

(8128, 10)

In [13]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

**3. OneHotEncoding using Sklearn**

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=2)

In [15]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
ohe = OneHotEncoder(drop='first', sparse_output=False,dtype=np.int32)

In [18]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [19]:
X_test_new = ohe.fit_transform(X_test[['fuel', 'owner']])

In [20]:
X_train_new.shape

(6502, 7)

In [21]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [22]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

**4. OHE with Top Categories**

In [23]:
counts = df['brand'].value_counts()

In [24]:
df['brand'].nunique()
threshold = 100

In [25]:
repl = counts[counts <= threshold].index

In [26]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).head()

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0